name: Update README

on:
  schedule:
    - cron: '0 */12 * * *' # Se ejecuta cada 12 horas en punto
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    name: Update Profile README
    runs-on: ubuntu-latest
    permissions:
      contents: write # CRUCIAL: Permite que el bot edite tu README
    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
